global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-app'
    scrape_interval: 10s
    static_configs:
      - targets: ['fastapi-app:8000']  # Docker service name
        labels:
          service: 'tasks-api'
          instance: 'fastapi-app-1'
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 20s
    scrape_timeout: 15s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 20s
    scrape_timeout: 15s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 20s
    scrape_timeout: 15s